# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db55f8195ac45bc9a421507b4a27fb5499ad680be0e96f41f641925f5832ba8c463a1be27a93c8518b9f9a5d6445d58557d9d624dd73dfa5ccb4aa7a28cd621e

test:
  secret_key_base: ab943b92d323a53eb0f177d14d2ff534d0a3d916ee40681fa682fba308451fd2ab97452ecf474579f426fde818512f405d330ec8438e09af6a66ac0e19b1b691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
